create table sensor(
  id_sensor int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30) unique
);

create table measurements(
    id_measurements int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature numeric,
    raining boolean,
    date_time timestamp default now(),
    sensor varchar(30) REFERENCES sensors(name)
);